Update for Olympia
Joystream/status-endpoint-joystream pull request #26
Opened 2022-03-09 15:36 UTC by DzhideX

Changes:
- Set `@joystream/types` package version to `^0.18.1`
- Update `councilData` function to work with the new types (used [this code](https://github.com/Joystream/pioneer/blob/olympia/packages%2Fui%2Fsrc%2Fcouncil%2Fhooks%2FuseElectionStage.ts) as inspiration)
- Removed memo from `transfers.ts` and from the `Exchange` type in `db.ts`

2022-03-10 09:54 UTC, Lezek123 requested changes
I haven't noticed this before, because the old Pioneer was using `balances.transfer` method for transfers, but both https://polkadot.js.org and CLI use `balances.transferKeepAlive` and those extrinsics are not currently recognized by the transactions processor. This needs to be fixed.

Another issue I noticed while testsing is that automatic burns seem to have stopped working:
```
2022-03-10 10:45:06        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
2022-03-10 10:45:06             DRR: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
```
This is probably because in Olympia the _existential deposit_ of **10 JOY** was introduced, which prevents making a transaction with a tip that's > `current_balance - 10 JOY`

2022-03-12 08:35 UTC, DzhideX commented
I've added `transferKeepAlive` to the methods check so that now it is being recognized correctly. 

As for the `autoburn` issue, I fixed it in such a way where it always tries to keep a balance of `10 JOY`. This means, either the first burn would be for `10 JOY` less or how I actually intended it to be is that the one setting up the server needs to send `10 JOY` to it and then it should theoretically work without any problems. I don't know if you can think of a better solution for that?

2022-03-22 13:22 UTC, Lezek123 requested changes

2022-03-23 18:27 UTC, DzhideX commented on src/joyApi.ts
> +    const EXISTENTIAL_DEPOSIT = 10;
Indeed, I wanted to ask if it was possible to get that data from the api directly but forgot. Thank you!

2022-03-24 15:57 UTC, Lezek123 approved these changes
LGTM

2022-03-29 10:58 UTC, bwhm approved these changes
:+1:

2022-03-29 10:58 UTC, merged